name: Newman Run

on:
  pull_request:
    branches:
    - master

jobs:
  newman:
    runs-on: ubuntu-latest
    steps:
      - uses: matt-ball/newman-action@0.0.16
        with:
          postmanApiKey: ${{ secrets.postmanApiKey }}
          collection: 5922408-c22ef764-b464-424c-8702-750343478723
          environment: 5922408-228c7edd-fc15-4f68-9665-a35d7df6945b
