name: Newman Run

on:
  pull_request:
    branches:
    - master

jobs:
  newman:
    runs-on: ubuntu-latest
    steps:
      - uses: matt-ball/newman-action@0.0.7
        with:
          collection: https://www.getpostman.com/collections/89ba0c919d73304be70d
          environment: postman_environment.json
