name: Newman

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 6
      - run: npm i -g newman
      - run: newman run <<collection file/url>> -e <<environment file/url>>
      # https://github.com/postmanlabs/newman
