name: Tests

on:
  pull_request:
    branches:
    - master

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: matt-ball/newman-action@v0.2.0
        with:
          collection: postman_collection.json
          environment:  postman_environment.json
