name: Tests

on:
  pull_request:
    branches:
    - master

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
      - name: Install deps and start server
        run: |
          make bootstrap
          make background
      - name: Lint code
        run: make lint
      - uses: matt-ball/newman-action@master
        with:
          apiKey: ${{ secrets.POSTMANAPIKEY }}
          collection: 10016724-a773a380-c718-4b42-ad21-2acc80d9b01c
          environment: postman_environment.json
