name: Tests

on:
  pull_request:
    branches:
    - master

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
      - name: Install deps and start server
        run: |
          make bootstrap
          make background
      - name: Lint code
        run: make lint
      - uses: matt-ball/newman-action@v0.2.4
        with:
          apiKey: ${{ secrets.POSTMANAPIKEY }}
          collection: 10016724-b5432e7f-b55a-4f5a-9878-3c6c19e8ab6f
          environment: postman_environment.json
          insecure: true
      
