name: Tests

on:
  pull_request:
    branches:
    - master

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
      - name: Install deps and start server
        run: |
          make bootstrap
          make background
      - name: Lint code
        run: make lint
      - uses: matt-ball/newman-action@v0.2.4
        with:
          apiKey: ${{ secrets.POSTMANAPIKEY }}
          collection: 10016724-95796187-1155-48d3-8aa8-1c3e61f76fd8
          environment: 10016724-9f2cb19b-05e2-4515-96fa-2eb56a5d1e43
          insecure: true
      
