name: Update Postman Collection

on:
  push:
    branches:
    - master

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@master
    - name: Update collection
      run: |
        make bootstrap
        npm i -g @matt.ball/postman-cli
        echo ${{ secrets.CLI }} > .postman.json
        pwd
        ls -lsa
        postman update
