name: Update Postman Collection

on:
  push:
    branches:
    - master

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@master
    - name: Update collection
      run: |
        npm i -g @matt.ball/postman-cli
        ${{ secrets.CLI }} > .postman.json
        postman sync
